[package]
name = "SteamScraper"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
flamegraph = "0.6.7"
reqwest = "0.12.12"
tl = "0.7.8"
tokio = { version="1.43.0", features=["full"] }
